# Generated by Django 6.1 on 2026-08-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0002_healthcheck"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="check_interval",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
