# Generated by Django 6.1 on 2026-08-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0003_monitor_check_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthcheck",
            name="check_type",
            field=models.CharField(default="user", max_length=20),
        ),
    ]
